# Generated by Django 2.0 on 2017-12-31 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=5)),
                ('image_URL', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=100)),
                ('image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Group')),
            ],
        ),
    ]
