# Generated by Django 2.0 on 2018-01-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180102_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_URL',
            new_name='url',
        ),
    ]
