# Generated by Django 2.0 on 2018-01-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180102_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_fave',
            field=models.BooleanField(default=False),
        ),
    ]
